# Generated by Django 4.1.5 on 2023-01-14 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dininglocation',
            name='meal_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.mealperiod'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.rating'),
        ),
        migrations.AlterField(
            model_name='mealperiod',
            name='items_offered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.fooditem'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
