# Generated by Django 4.1.5 on 2023-01-14 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delta', '0002_alter_dininglocation_meal_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='dininglocation',
            name='meal_period',
        ),
        migrations.RemoveField(
            model_name='mealperiod',
            name='items_offered',
        ),
        migrations.AddField(
            model_name='mealperiod',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.dininglocation'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AlterField(
            model_name='rating',
            name='when',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.mealperiod'),
        ),
        migrations.AddField(
            model_name='rating',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delta.menuitem'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
