# Generated by Django 4.1.5 on 2023-01-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0003_menuitem_remove_dininglocation_meal_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininglocation',
            name='identifier',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
