# Generated by Django 4.1.5 on 2023-01-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0006_alter_mealperiod_location_alter_menuitem_meal_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealperiod',
            name='uid',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
